# Generated by Django 2.2.4 on 2019-08-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200, verbose_name='عنوان وب سایت')),
                ('site_desc', models.CharField(max_length=200, verbose_name='توضیح کوتاه')),
                ('about', models.TextField(verbose_name='درباره ما')),
                ('contact', models.TextField(verbose_name='تماس با ما')),
            ],
            options={
                'verbose_name': 'اطلاعات وب سایت',
                'verbose_name_plural': 'مشخصات وب سایت',
            },
        ),
    ]
