# Generated by Django 2.2.4 on 2019-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_location',
            field=models.TextField(blank=True, help_text='در صورت داشتن مکان فیزیکی می توانید آدرس گوگل خود را وارد نمایید', verbose_name='آدرس نقشه گوگل'),
        ),
    ]
