# Generated by Django 2.2.4 on 2019-08-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_site_site_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان وب سایت')),
                ('desc', models.CharField(max_length=200, verbose_name='توضیح کوتاه')),
                ('about', models.TextField(verbose_name='درباره ما')),
                ('contact', models.TextField(verbose_name='تماس با ما')),
                ('location', models.TextField(blank=True, help_text='در صورت داشتن مکان فیزیکی می توانید آدرس گوگل خود را وارد نمایید', verbose_name='آدرس نقشه گوگل')),
            ],
            options={
                'verbose_name': 'اطلاعات وب سایت',
                'verbose_name_plural': 'مشخصات وب سایت',
            },
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
