# Generated by Django 2.2.4 on 2019-08-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
