# Generated by Django 2.2.5 on 2019-09-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
    ]
